# Generated by Django 4.2.30 on 2026-04-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('created_by', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='模块描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
                'ordering': ['project', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='全局变量')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='公共请求参数')),
                ('request_hooks', models.JSONField(blank=True, default=dict, verbose_name='请求Hooks')),
                ('response_hooks', models.JSONField(blank=True, default=dict, verbose_name='响应Hooks')),
                ('env_type', models.CharField(choices=[('DEV', '开发环境'), ('QA', '测试环境'), ('PROD', '生产环境')], default='DEV', max_length=10, verbose_name='环境类型')),
                ('created_by', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.module', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'ordering': ['module', 'name'],
            },
        ),
    ]
