# Generated by Django 4.2.30 on 2026-04-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('url', models.URLField(max_length=500, verbose_name='请求URL')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('extractors', models.JSONField(blank=True, default=dict, verbose_name='提取器')),
                ('assertions', models.JSONField(blank=True, default=list, verbose_name='断言')),
                ('setup_hooks', models.JSONField(blank=True, default=list, verbose_name='前置Hooks')),
                ('teardown_hooks', models.JSONField(blank=True, default=list, verbose_name='后置Hooks')),
                ('is_parameterized', models.BooleanField(default=False, verbose_name='是否参数化')),
                ('created_by', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='api.module', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['module', 'name'],
            },
        ),
    ]
