# Generated by Django 4.2.30 on 2026-04-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDTSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('source_type', models.CharField(choices=[('JSON', 'JSON'), ('YAML', 'YAML'), ('CSV', 'CSV'), ('DB', '数据库')], default='JSON', max_length=10, verbose_name='数据源类型')),
                ('file_path', models.CharField(blank=True, default='', help_text='JSON/YAML/CSV 文件的相对路径', max_length=500, verbose_name='文件路径')),
                ('db_query', models.TextField(blank=True, default='', help_text='仅数据库类型使用，SQL 查询语句', verbose_name='数据库查询')),
                ('content', models.TextField(blank=True, default='', help_text='直接内嵌的 JSON/YAML 数据', verbose_name='数据内容')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DDT 数据源',
                'verbose_name_plural': 'DDT 数据源',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='ddt_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='api.ddtsource', verbose_name='DDT数据源'),
        ),
    ]
