# Generated by Django 4.2.30 on 2026-04-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ddtsource_testcase_ddt_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='场景描述')),
                ('created_by', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='api.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试场景',
                'verbose_name_plural': '测试场景',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序序号')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_cases', to='api.scene', verbose_name='所属场景')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_cases', to='api.testcase', verbose_name='关联用例')),
            ],
            options={
                'verbose_name': '场景用例',
                'verbose_name_plural': '场景用例',
                'ordering': ['scene', 'order_index'],
            },
        ),
    ]
