# Generated by Django 4.2.30 on 2026-04-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scene_scenecase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('SYNC', '同步执行'), ('ASYNC', '异步执行'), ('SCHEDULE', '定时任务')], default='SYNC', max_length=10, verbose_name='执行类型')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '执行失败')], default='PENDING', max_length=10, verbose_name='状态')),
                ('scope', models.CharField(choices=[('TESTCASE', '单用例'), ('MODULE', '模块'), ('PROJECT', '项目'), ('SCENE', '场景')], default='TESTCASE', max_length=10, verbose_name='执行范围')),
                ('execute_env', models.CharField(choices=[('DEV', '开发环境'), ('QA', '测试环境'), ('PROD', '生产环境')], default='DEV', max_length=10, verbose_name='执行环境')),
                ('cron_expression', models.CharField(blank=True, default='', max_length=100, verbose_name='Cron表达式')),
                ('email_notify', models.BooleanField(default=False, verbose_name='邮件通知')),
                ('report_name', models.CharField(blank=True, default='', max_length=200, verbose_name='报告名称')),
                ('created_by', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.module', verbose_name='模块')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.project', verbose_name='项目')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.scene', verbose_name='场景')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.testcase', verbose_name='用例')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed', models.IntegerField(default=0, verbose_name='失败数')),
                ('error', models.IntegerField(default=0, verbose_name='错误数')),
                ('skipped', models.IntegerField(default=0, verbose_name='跳过数')),
                ('duration', models.FloatField(default=0, verbose_name='执行耗时(秒)')),
                ('report_path', models.CharField(blank=True, default='', max_length=500, verbose_name='报告路径')),
                ('log', models.TextField(blank=True, default='', verbose_name='执行日志')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '任务结果',
                'verbose_name_plural': '任务结果',
                'ordering': ['-executed_at'],
            },
        ),
    ]
