# Generated by Django 4.2.30 on 2026-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_taskresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['module', 'name'], 'verbose_name': '环境', 'verbose_name_plural': '环境'},
        ),
        migrations.AddField(
            model_name='config',
            name='base_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='环境地址'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=100, verbose_name='环境名称'),
        ),
    ]
