# Generated by Django 4.2.30 on 2026-04-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_base_url_to_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='变量名')),
                ('value', models.CharField(blank=True, default='', max_length=500, verbose_name='变量值')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_configs', to='api.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目配置',
                'verbose_name_plural': '项目配置',
                'ordering': ['project', 'key'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
