# Generated by Django 4.2.30 on 2026-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_projectconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='body_type',
            field=models.CharField(choices=[('none', 'None'), ('json', 'JSON'), ('form-data', 'Form-Data'), ('x-www-form-urlencoded', 'x-www-form-urlencoded'), ('binary', 'Binary')], default='json', max_length=30, verbose_name='请求体类型'),
        ),
    ]
