# Generated by Django 4.2.30 on 2026-04-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_testcase_body_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('PUBLIC', '公共脚本'), ('PROJECT', '项目脚本')], max_length=10, verbose_name='作用域')),
                ('name', models.CharField(max_length=200, verbose_name='脚本名称')),
                ('language', models.CharField(default='python', max_length=20, verbose_name='语言')),
                ('content', models.TextField(blank=True, default='', verbose_name='脚本内容')),
                ('function_index', models.JSONField(blank=True, default=list, verbose_name='函数索引')),
                ('is_system_generated', models.BooleanField(default=True, verbose_name='系统生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='api.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '脚本资产',
                'verbose_name_plural': '脚本资产',
                'ordering': ['scope_type', 'name'],
            },
        ),
    ]
